# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application
permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:latest
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: 1234
          POSTGRES_PORT: 5432
          POSTGRES_USER: admin
          POSTGRES_DB: dvdrental
        ports:
          # maps tcp port 5432 on service container to the host
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::308342534802:role/s3-access
        role-duration-seconds: 900 # the ttl of the session, in seconds.
        aws-region: sa-east-1 # use your region here.
    # You can now execute commands that use the credentials👇
    - name: download file
      run: aws s3 cp s3://josseed-bucket/restore.sql .
    - name: Install PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install --yes postgresql-client
    - name: migrate database
      run: PGPASSWORD=1234 psql -h localhost -U admin -d dvdrental -a -f restore.sql
    - name: cleaning database
      run: |
        PGPASSWORD=1234 psql -h localhost -U admin -d postgres -c 'DROP DATABASE dvdrental;'
        rm restore.sql
    


